export const recipeCategories = {
    favourites: ["Cowboy Chocolate Chip", "Apple Crisp", "Best Brownies"],
    breads: [
        "Banana Bread",
        "Buns",
        "Nauvoo Bread",
        "Yorkshire Pudding",
        "Zucchini Bread",
    ],

    cakes: [
        "Almond Meringue Cake",
        "Carrot Pineapple Cake",
        "Cheesecake for a Crowd",
        "Chocolate Cake (All Fools)",
        "Chocolate Cake (Easy Mix)",
        "Chocolate Pumpkin Cake",
        "Chocolate Truffle Cheesecake",
        "Christmas Fruit Cake",
        "Frosting (Aunt Jane)",
        "Frosting (Caramel)",
        "Frosting (Chocolate Butterscotch)",
        "German Chocolate Cake",
        "Hot Fudge Pudding Cake",
        "Lemon Cake",
        "Lemon Pudding Cake",
        "Tomato Soup Cake",
        "White Cake",
    ],
    candy: [
        "Caramels",
        "Chocolates (Fondant)",
        "Easter Eggs",
        "Fondant",
        "Licorice Toffee",
        "Stretch Candy",
    ],
    cookies: [
        "Boiled Raisin Cookies",
        "Canadian Jam Cookies",
        "Coconut-Oatmeal Crisp Cookies",
        "Cowboy Chocolate Chip",
        "Double Chocolate Chip Cookies (Pam's Cookies)",
        "Easy Shortbread",
        "Ginger Cream Cookies",
        "Gingerbread for Houses",
        "Gingerbread Men",
        "Lemon Crinkle Cookies",
        "Molasses Crinkles",
        "No-Bake Cookies",
        "Oreo Cookies",
        "Peanut Butter Cookies",
        "Puffed Wheat Squares",
        "Pumpkin Chocolate Chip Cookies",
        "Rolo Cookies",
        "Sugar Cookies",
    ],
    desserts: [
        "Apple Crisp",
        "Best Brownies",
        "Brownie Pudding",
        "Caramel Popcorn",
        "Chocolate Hot Fudge",
        "Cookie Dough Brownies",
        "Date Crumble",
        "Frozen Dessert",
        "Jelly Roll",
        "Lemon Angel Pie",
        "Lemon Curd Pie",
        "Lemon Mousse Pie",
        "Mini Cheesecakes",
        "Pecan Pie",
        "Popcorn (Dorothy Karo Crazy Crunch)",
        "Puffed Wheat Squares",
        "Raised Doughnuts",
        "Special K Treats",
    ],
    "main dishes": [
        "Baked Salmon",
        "BBQ Ribs (Sweet)",
        "Cafe Rio Pork and Tomatillo Dressing",
        "Chinese Casserole",
        "Lasagna (Beef)",
        "Lasagna (Chicken)",
        "Macaroni & Cheese",
        "Molded Beef Ring",
        "Mongolian Beef",
        "Mozzarella Pork Chops",
        "Oriental Chicken Wings",
        "Pasta with Italian Sausage & Cheese Sauce",
        "Pastry",
        "Pizza Spread (Mexican)",
        "Pork Tenderloin (Ginger Marinated)",
        "Roast Pork Boulanger",
        "Sloppy Joes",
        "Spanish Rice",
        "Sweet & Sour Meat Balls",
        "Tomato Meatloaf",
        "Tourtiere",
    ],
    miscellaneous: [
        "Antipasto",
        "Beets (Bottled)",
        "Beets (Pickled)",
        "Cheeseball",
        "Party Cheeseball",
        "Shrimp Toast",
        "Tartar Sauce",
        "Wassail",
    ],
    muffins: [
        "Banana Oatmeal Muffins",
        "Chocolate Chip Muffins",
        "Cranberry Muffins",
    ],
    salads: [
        "Chicken Pasta Salad",
        "Cranberry Jello",
        "Crazy Bean Salad",
        "Frog Eye Salad",
        "Greek Pasta Salad",
        "Honey-Lime Chicken and Apple Salad",
        "Mandarin Tossed Salad",
        "Pomegranate Salad",
        "Potato Salad Dressing",
        "Romaine with Oranges and Pecans",
        "Strawberry Salad",
        "That Good Salad",
    ],
    sandwiches: [
        "Almond Chicken Salad Sandwiches",
        "Chicken Croissant",
        "Egg Salad Tea Sandwiches",
        "Fancy Sandwiches",
        "Pineapple Nut Tea Sandwiches",
    ],
    soups: [
        "Cream of Wild Rice",
        "Taco Soup",
        "Tomato Bisque",
        "Tomato Bisque (Creamed)",
    ],
    vegetables: ["Funeral Potatoes", "Wild Rice and Mushroom"],
};
