const cakeRecipes = {
    all_fools_chocolate_cake: {
        title: "All Fools Chocolate Cake",
        servings: 1,
        ingredients: [
            { item: "white flour", amount: "2 1/2", unit: "cups" },
            { item: "whole wheat flour", amount: "1/2", unit: "cup" },
            { item: "cocoa", amount: "1/2", unit: "cup" },
            { item: "baking soda", amount: 2, unit: "tsp" },
            { item: "salt", amount: 2, unit: "tsp" },
            { item: "sugar", amount: 2, unit: "cups" },
            { item: "sour milk or buttermilk", amount: 1, unit: "cup" },
            { item: "oil", amount: 1, unit: "cup" },
            { item: "eggs", amount: 2 },
            { item: "boiling water", amount: 1, unit: "cup" },
            { item: "vanilla", amount: 1, unit: "tsp" },
        ],
        instructions: [
            "Stir together with mixer all ingredients except boiling water and vanilla.",
            "Blend in boiling water and vanilla.",
            "Bake at 350°F for 30-50 minutes.",
        ],
    },
    almond_meringue_cake: {
        title: "Almond Meringue Cake",
        servings: 1,
        ingredients: [
            { item: "margarine", amount: "3/4", unit: "cup" },
            { item: "sugar", amount: "3/4", unit: "cup" },
            { item: "egg yolks", amount: 6 },
            { item: "vanilla", amount: 1, unit: "tsp" },
            { item: "salt", amount: "1/2", unit: "tsp" },
            { item: "baking powder", amount: "1 1/2", unit: "tsp" },
            { item: "flour", amount: "1 1/2", unit: "cups" },
            { item: "milk", amount: "7 1/2", unit: "tbsp" },
            { item: "egg whites", amount: 6 },
            { item: "sugar (for meringue)", amount: "1 1/2", unit: "cups" },
            { item: "sliced almonds", amount: 1, unit: "to taste" },
        ],
        instructions: [
            "Cream margarine, add sugar, then egg yolks, and vanilla.",
            "Add remaining ingredients and mix.",
            "Grease 9x13 cake pan. Pour in batter.",
            "In a separate bowl whip 6 egg whites. Add 1 1/2 cups sugar and continue whipping.",
            "Spread meringue over cake batter and sprinkle with sliced almonds.",
            "Bake at 350°F.",
            "Serve with whipped cream or ice cream and berries.",
        ],
    },
    carrot_pineapple_cake: {
        title: "Carrot-Pineapple Cake",
        servings: 1,
        ingredients: [
            { item: "flour", amount: 3, unit: "cups" },
            { item: "sugar", amount: 2, unit: "cups" },
            { item: "cinnamon", amount: 2, unit: "tsp" },
            { item: "baking soda", amount: "1 1/2", unit: "tsp" },
            { item: "salt", amount: "1 1/2", unit: "tsp" },
            { item: "baking powder", amount: 1, unit: "tsp" },
            { item: "crushed pineapple", amount: 8, unit: "oz" },
            { item: "eggs", amount: 3 },
            { item: "cooking oil", amount: "1 1/2", unit: "cups" },
            { item: "vanilla", amount: 2, unit: "tsp" },
            { item: "chopped nuts", amount: "1 1/2", unit: "cups" },
            { item: "raw carrots, grated", amount: 2, unit: "cups" },
        ],
        instructions: [
            "Mix together all dry ingredients.",
            "Drain pineapple; reserve syrup.",
            "Add pineapple syrup to dry mixture, add eggs, oil, and vanilla; beat 3 minutes.",
            "Stir in pineapple, nuts, and carrots.",
            "Bake in greased and floured 12-cup Bundt Pan at 325°F for about 1 1/2 hours or until cake tests done.",
            "Cool 10-15 minutes; turn out on wire rack or serving plate to complete cooling.",
        ],
    },
    cheesecake_for_a_crowd: {
        title: "Cheesecake for a Crowd",
        servings: 1,
        ingredients: [
            { item: "cream cheese", amount: 8, unit: "oz" },
            { item: "powdered sugar", amount: "3/4", unit: "cup" },
            { item: "cool whip", amount: 16, unit: "oz" },
        ],
        instructions: [
            "Whip cream cheese and powdered sugar until smooth.",
            "Add cool whip and mix well.",
        ],
    },
    cheesecake_for_a_crowd_2: {
        title: "Cheesecake for a Crowd (Version 2)",
        servings: "24-30",
        ingredients: [
            { item: "white cake mix", amount: 1, unit: "pkg" },
            { item: "cream cheese, softened", amount: 16, unit: "oz" },
            { item: "powdered sugar", amount: 4, unit: "cups" },
            { item: "whipped cream", amount: 1, unit: "pt" },
            {
                item: "cherry, raspberry, or strawberry pie filling",
                amount: 16,
                unit: "oz",
            },
        ],
        instructions: [
            "Preheat oven to 350°F. Grease and flour two 9x13 inch baking pans.",
            "Prepare cake according to package directions and pour half of cake batter in each pan.",
            "Bake for 20 minutes or until cake tests done. Remove from oven and cool.",
            "Whip cream cheese and powdered sugar together till fluffy. Add whipped cream.",
            "Spread mixture onto both cakes.",
            "Spread pie filling on top of cream cheese layer.",
            "Refrigerate till ready to serve.",
        ],
    },
    chocolate_pumpkin_cake: {
        title: "Chocolate Pumpkin Cake",
        servings: 1,
        ingredients: [
            { item: "butter", amount: "3/4", unit: "cup" },
            { item: "white sugar", amount: 1, unit: "cup" },
            { item: "eggs", amount: 3 },
            { item: "egg yolk", amount: 1 },
            { item: "flour", amount: "1 1/2", unit: "cups" },
            { item: "cocoa", amount: "2/3", unit: "cup" },
            { item: "baking powder", amount: 2, unit: "tsp" },
            { item: "baking soda", amount: 1, unit: "tsp" },
            { item: "salt", amount: "1/2", unit: "tsp" },
            { item: "pumpkin", amount: 1, unit: "cup" },
            { item: "buttermilk", amount: "1/2", unit: "cup" },
            { item: "vanilla", amount: 2, unit: "tsp" },
        ],
        instructions: [
            "Cream butter and sugar together.",
            "Beat in eggs and egg yolk one at a time.",
            "Sift together flour, cocoa, baking powder, baking soda, and salt.",
            "Stir together pumpkin, buttermilk, and vanilla.",
            "Add flour and buttermilk mixture alternately in thirds to creamed mixture.",
            "Bake at 375°F for 35 minutes.",
        ],
    },
    chocolate_pumpkin_cake_frosting: {
        title: "Chocolate Pumpkin Cake Frosting",
        servings: 1,
        ingredients: [
            { item: "cream cheese", amount: 6, unit: "oz" },
            { item: "brown sugar", amount: 1, unit: "cup" },
            { item: "icing sugar", amount: "1 1/2", unit: "cups" },
            { item: "cocoa", amount: "2 1/4", unit: "tsp" },
            { item: "cinnamon", amount: "1/4", unit: "tsp" },
            { item: "vanilla", amount: "3/4", unit: "tsp" },
            { item: "cream", amount: "1 1/2", unit: "cups" },
            { item: "icing sugar", amount: "3/4", unit: "cup" },
            { item: "orange food coloring", amount: "1/4", unit: "tsp" },
        ],
        instructions: [
            "Cream together cream cheese, brown sugar, icing sugar, cocoa, cinnamon, and vanilla.",
            "Whip cream with icing sugar and orange food coloring.",
            "Fold the creamed mixture and the whipped cream together.",
            "Ice the cake and chill for 30 minutes.",
        ],
    },
    chocolate_pumpkin_cake_glaze: {
        title: "Chocolate Pumpkin Cake Glaze",
        servings: 1,
        ingredients: [
            { item: "bitter chocolate", amount: 4, unit: "oz" },
            { item: "butter", amount: 1, unit: "tbsp" },
            { item: "syrup", amount: 3, unit: "tbsp" },
            { item: "cream", amount: "1/2", unit: "cup" },
        ],
        instructions: [
            "Bring cream to a boil.",
            "Pour over chocolate, butter, and syrup.",
            "Let stand for 3 minutes.",
            "Gently stir using a whisk until smooth.",
            "Let stand until thickened.",
            "Pour onto the center of the frosted cake.",
            "Smooth out to the edges to allow glaze to drip over the sides.",
        ],
    },
    chocolate_truffle_cheesecake: {
        title: "Chocolate Truffle Cheesecake",
        servings: 1,
        ingredients: [
            { item: "Oreo Baking Crumbs", amount: "1 1/4", unit: "cups" },
            { item: "melted butter", amount: "1/4", unit: "cup" },
            { item: "cream cheese, softened", amount: 750, unit: "g" },
            { item: "sugar", amount: 1, unit: "cup" },
            { item: "vanilla", amount: 1, unit: "tsp" },
            {
                item: "semi-sweet chocolate, melted and cooled",
                amount: 6,
                unit: "squares",
            },
            { item: "eggs", amount: 3 },
        ],
        instructions: [
            "Combine crumbs and butter; press onto bottom of 9-inch spring form pan.",
            "Beat cream cheese, sugar and vanilla on medium speed until well blended.",
            "Blend in melted chocolate.",
            "Add eggs one at a time; mix just until blended. Pour over crust.",
            "Bake at 350°F for 45 to 50 minutes or until centre is almost set.",
            "Cool completely, then refrigerate 3 hours or overnight.",
        ],
    },
    christmas_fruit_cake: {
        title: "Christmas Fruit Cake (Wedding Cake)",
        servings: 1,
        ingredients: [
            { item: "butter", amount: 1, unit: "lb" },
            { item: "sugar", amount: 2, unit: "cups" },
            { item: "eggs", amount: 12 },
            { item: "soda", amount: 1, unit: "tsp" },
            { item: "cinnamon", amount: 2, unit: "tsp" },
            { item: "nutmeg", amount: 2, unit: "tsp" },
            { item: "flour", amount: 4, unit: "cups" },
            { item: "molasses or corn syrup", amount: "2/3", unit: "cup" },
            { item: "puff raisins", amount: 1, unit: "package" },
            { item: "raisins", amount: 3, unit: "lbs" },
            { item: "walnuts", amount: 1, unit: "lb" },
            { item: "blanched almonds", amount: 1, unit: "lb" },
            { item: "candied pineapple", amount: 1, unit: "lb" },
            { item: "maraschino cherries", amount: 1, unit: "pt" },
        ],
        instructions: [
            "Cream butter and sugar, add eggs, add juice from the cherries.",
            "Add soda to molasses, beat until thick.",
            "Sift flour on fruit and add to cake batter.",
            "Line pans with foil and wax paper for baking.",
            "Bake at 275°F for 3 hours.",
            "Place pan of water in oven while baking.",
        ],
    },
    easy_mix_chocolate_cake: {
        title: "Easy Mix Chocolate Cake",
        servings: 1,
        ingredients: [
            { item: "oil", amount: "1/3", unit: "cup" },
            { item: "Baker's chocolate", amount: 2, unit: "squares" },
            { item: "water", amount: "3/4", unit: "cup" },
            { item: "sugar", amount: 1, unit: "cup" },
            { item: "egg", amount: 1 },
            { item: "flour", amount: "1 1/4", unit: "cups" },
            { item: "salt", amount: "1/2", unit: "tsp" },
            { item: "baking soda", amount: "1/2", unit: "tsp" },
            { item: "vanilla", amount: 1, unit: "tsp" },
            { item: "chocolate chips", amount: 6, unit: "oz" },
            { item: "nuts", amount: "1/3", unit: "cup" },
        ],
        instructions: [
            "Measure oil and add chocolate. Melt them together in the microwave.",
            "Mix first 9 ingredients together.",
            "Pour in an 8-inch square pan.",
            "Sprinkle chocolate chips and nuts on top.",
            "Bake at 350°F for 40 minutes.",
        ],
    },
    hot_fudge_pudding_cake: {
        title: "Hot Fudge Pudding Cake",
        servings: 1,
        ingredients: [
            { item: "flour", amount: 1, unit: "cup" },
            { item: "baking powder", amount: 2, unit: "tsp" },
            { item: "salt", amount: "1/4", unit: "tsp" },
            { item: "sugar", amount: "3/4", unit: "cup" },
            { item: "cocoa", amount: 2, unit: "tbsp" },
            { item: "milk", amount: "1/2", unit: "cup" },
            { item: "shortening, melted (or oil)", amount: 2, unit: "tbsp" },
            { item: "chopped nuts", amount: 1, unit: "cup" },
            { item: "brown sugar, packed", amount: 1, unit: "cup" },
            { item: "cocoa", amount: "1/4", unit: "cup" },
            { item: "hot water", amount: "1 3/4", unit: "cups" },
            { item: "vanilla", amount: 1, unit: "tsp" },
        ],
        instructions: [
            "Blend flour, baking powder, salt, sugar, and 2 tbsp cocoa in a bowl.",
            "Stir in milk and shortening.",
            "Blend in nuts.",
            "Spread in greased 9x9 pan.",
            "Sprinkle with mixture of brown sugar and 1/4 cup cocoa.",
            "Pour hot water over entire batter.",
            "Bake 35-40 minutes at 350°F.",
            "Serve warm with vanilla ice cream.",
        ],
    },
    jelly_roll: {
        title: "Jelly Roll",
        servings: 1,
        ingredients: [
            { item: "eggs", amount: 6 },
            { item: "sugar", amount: "7/8", unit: "cup" },
            { item: "pastry flour", amount: 1, unit: "cup" },
            { item: "baking powder", amount: "2 1/4", unit: "tsp" },
            { item: "hot water", amount: "1 1/2", unit: "tbsp" },
        ],
        instructions: [
            "Beat egg yolks and 1 whole egg until light.",
            "Add sugar and hot water.",
            "Stir in sifted flour and baking powder.",
            "Fold in beaten egg whites to which 1/4 cup sugar has been added.",
            "Pour in a wax paper lined cookie sheet (no grease). Do not trim the edges.",
            "Bake at 375°F for 12 minutes.",
            "Remove from oven and turn out on a towel covered in wax paper sprinkled with icing sugar.",
            "Sprinkle top with icing sugar and roll.",
            "Cool then spread with lemon filling or your favorite jelly.",
        ],
    },
    lemon_cake: {
        title: "Lemon Cake",
        servings: 2,
        ingredients: [
            { item: "butter", amount: 1, unit: "cup" },
            { item: "sugar", amount: 2, unit: "cups" },
            { item: "eggs", amount: 4 },
            { item: "lemon zest", amount: "1/3", unit: "cup" },
            { item: "flour", amount: 3, unit: "cups" },
            { item: "baking powder", amount: "1/2", unit: "tsp" },
            { item: "baking soda", amount: "1/2", unit: "tsp" },
            { item: "salt", amount: 1, unit: "tsp" },
            { item: "lemon juice", amount: "1/4", unit: "cup" },
            { item: "buttermilk", amount: "3/4", unit: "cup" },
            { item: "vanilla", amount: 1, unit: "tsp" },
        ],
        instructions: [
            "Cream butter and sugar.",
            "Add eggs and lemon zest.",
            "Sift flour, baking powder, baking soda, and salt.",
            "Combine lemon juice, buttermilk, and vanilla.",
            "Alternately add flour and buttermilk mixture to batter, beginning and ending with flour.",
            "Bake at 350°F for 45-60 minutes in two 8 1/2 x 4 1/2 x 2 1/2 loaf pans.",
            "Cool for 10 minutes.",
        ],
    },
    lemon_cake_syrup: {
        title: "Lemon Cake Syrup",
        servings: 2,
        ingredients: [
            { item: "lemon juice", amount: "1/2", unit: "cup" },
            { item: "sugar", amount: "1/2", unit: "cup" },
        ],
        instructions: [
            "Heat lemon juice and sugar until sugar is dissolved.",
            "Pour over warm cake.",
        ],
    },
    lemon_cake_glaze: {
        title: "Lemon Cake Glaze",
        servings: 2,
        ingredients: [
            { item: "powdered sugar", amount: 2, unit: "cups" },
            { item: "lemon juice", amount: "3 1/2", unit: "tbsp" },
        ],
        instructions: [
            "Whisk together powdered sugar and lemon juice until smooth.",
            "Pour over top of cake and let drizzle over sides.",
        ],
    },
    white_cake: {
        title: "White Cake",
        servings: 1,
        ingredients: [
            { item: "shortening", amount: "1/2", unit: "cup" },
            { item: "sugar", amount: 1, unit: "cup" },
            { item: "flour", amount: "1 3/4", unit: "cups" },
            { item: "baking powder", amount: 3, unit: "tsp" },
            { item: "salt", amount: "1/2", unit: "tsp" },
            { item: "milk", amount: 1, unit: "cup" },
            { item: "vanilla", amount: 1, unit: "tsp" },
            { item: "egg whites", amount: 3 },
        ],
        instructions: [
            "Mix together shortening, sugar, flour, baking powder, salt, milk, and vanilla.",
            "Fold in 3 beaten egg whites (stiff).",
            "Bake at 350°F for 30-35 minutes.",
        ],
    },
};

export default cakeRecipes;
