const cookieRecipes = {
    cowboy_chocolate_chip: {
        title: "Cowboy Chocolate Chip",
        servings: 2, // 2 dozen
        ingredients: [
            { item: "all-purpose flour", amount: "2 1/4", unit: "cups" },
            { item: "baking soda", amount: 1, unit: "tsp" },
            { item: "salt", amount: 1, unit: "tsp" },
            { item: "unsalted butter, softened", amount: 1, unit: "cup" },
            { item: "granulated sugar", amount: "3/4", unit: "cup" },
            { item: "brown sugar", amount: "3/4", unit: "cup" },
            { item: "vanilla extract", amount: 1, unit: "tsp" },
            { item: "large eggs", amount: 2 },
            { item: "semisweet chocolate chips", amount: 2, unit: "cups" },
        ],
        instructions: [
            "Preheat oven to 375°F (190°C).",
            "In a small bowl, whisk together the flour, baking soda, and salt.",
            "In a large bowl, cream together the butter, granulated sugar, brown sugar, and vanilla extract until smooth.",
            "Beat in the eggs one at a time.",
            "Gradually blend in the flour mixture.",
            "Stir in the chocolate chips.",
            "Drop by rounded tablespoons onto ungreased baking sheets.",
            "Bake for 9 to 11 minutes or until golden brown.",
            "Let stand for 2 minutes before removing to cool on wire racks.",
        ],
    },
    molasses_crinkles: {
        title: "Molasses Crinkles",
        servings: 2, // 2 dozen
        ingredients: [
            { item: "margarine", amount: "3/4", unit: "cup" },
            { item: "brown sugar", amount: 1, unit: "cup" },
            { item: "egg", amount: 1 },
            { item: "molasses", amount: "1/4", unit: "cup" },
            { item: "flour", amount: "2 1/4", unit: "cups" },
            { item: "baking soda", amount: 2, unit: "tsp" },
            { item: "salt", amount: "1/4", unit: "tsp" },
            { item: "cloves", amount: "1/2", unit: "tsp" },
            { item: "cinnamon", amount: 1, unit: "tsp" },
            { item: "ginger", amount: 1, unit: "tsp" },
            { item: "sugar (for rolling)" },
        ],
        instructions: [
            "Mix margarine, sugar, egg and molasses together.",
            "Add dry ingredients and mix well.",
            "Roll into balls and roll in sugar.",
            "Bake at 375°F for 10 to 12 minutes.",
        ],
    },
    lemon_crinkle_cookies: {
        title: "Lemon Crinkle Cookies",
        servings: 2, // 2 dozen
        ingredients: [
            { item: "butter, softened", amount: "1/2", unit: "cup" },
            { item: "sugar", amount: 1, unit: "cup" },
            { item: "vanilla", amount: "1/2", unit: "tsp" },
            { item: "egg", amount: 1 },
            { item: "lemon zest", amount: 1, unit: "tsp" },
            { item: "fresh lemon juice", amount: 1, unit: "tbsp" },
            { item: "salt", amount: "1/4", unit: "tsp" },
            { item: "baking powder", amount: "1/4", unit: "tsp" },
            { item: "baking soda", amount: "1/8", unit: "tsp" },
            { item: "flour", amount: "1 1/2", unit: "cups" },
            { item: "powdered sugar", amount: "1/2", unit: "cup" },
        ],
        instructions: [
            "Preheat oven to 350°F. Grease baking sheets.",
            "Cream butter and sugar together until light and fluffy.",
            "Whip in vanilla, egg, lemon zest, and juice.",
            "Combine all ingredients except powdered sugar.",
            "Roll 1 tablespoon of dough into a ball and roll in powdered sugar.",
            "Place on baking sheet.",
            "Bake for 9-11 minutes.",
            "Let cool on pan for 3 minutes before removing.",
        ],
    },
    no_bake_cookies: {
        title: "No-Bake Cookies",
        servings: 2, // 2 dozen
        ingredients: [
            { item: "milk", amount: "1/2", unit: "cup" },
            { item: "margarine", amount: "1/2", unit: "cup" },
            { item: "cocoa", amount: 4, unit: "tbsp" },
            { item: "sugar", amount: 2, unit: "cups" },
            { item: "rolled oats", amount: 3, unit: "cups" },
            { item: "nuts", amount: 1, unit: "cup" },
            { item: "coconut", amount: 1, unit: "cup" },
        ],
        instructions: [
            "Bring milk, margarine, cocoa, and sugar to a full rolling boil.",
            "Pour over oats, coconut, and nuts.",
            "Mix well.",
            "Drop on wax paper.",
        ],
    },
    puffed_wheat_squares: {
        title: "Puffed Wheat Squares",
        servings: 16, // Keeping original as it's not easily convertible to dozens
        ingredients: [
            { item: "brown sugar", amount: 1, unit: "cup" },
            { item: "corn syrup", amount: "1/2", unit: "cup" },
            { item: "butter", amount: "1/4", unit: "cup" },
            { item: "cocoa", amount: 2, unit: "tbsp" },
            { item: "vanilla", amount: 1, unit: "tsp" },
            { item: "puffed wheat", amount: 7, unit: "cups" },
        ],
        instructions: [
            "Mix brown sugar, corn syrup, butter, cocoa, and vanilla in a pot.",
            "Bring to a boil and cook no longer than 3 minutes.",
            "Pour over puffed wheat.",
            "Pack in greased pan.",
            "Cool before serving.",
        ],
    },
    oreo_cookies: {
        title: "Oreo Cookies",
        servings: 2, // 2 dozen
        ingredients: [
            { item: "devil's food cake mixes", amount: 2 },
            { item: "oil", amount: "2/3", unit: "cup" },
            { item: "eggs", amount: 4 },
            { item: "cream cheese frosting" },
        ],
        instructions: [
            "Mix together devil's food cake mixes, oil, and eggs.",
            "Bake at 350°F for 7-8 minutes. Cookie will look not quite cooked.",
            "Cool and put 2 cookies together with cream cheese frosting.",
        ],
    },
    peanut_butter_cookies: {
        title: "Peanut Butter Cookies",
        servings: 6, // 6 dozen
        ingredients: [
            { item: "shortening", amount: 1, unit: "cup" },
            { item: "sugar", amount: 1, unit: "cup" },
            { item: "brown sugar", amount: 1, unit: "cup" },
            { item: "eggs", amount: 2 },
            { item: "vanilla", amount: 1, unit: "tsp" },
            { item: "peanut butter", amount: 1, unit: "cup" },
            { item: "sifted flour", amount: 3, unit: "cups" },
            { item: "baking soda", amount: 2, unit: "tsp" },
            { item: "salt", amount: "1/2", unit: "tsp" },
        ],
        instructions: [
            "Mix all ingredients together.",
            "Form into balls.",
            "Press with fork.",
            "Bake at 375°F for 10 minutes.",
            "Cool slightly.",
        ],
    },
    boiled_raisin_cookies: {
        title: "Boiled Raisin Cookies",
        servings: 3, // 3 dozen
        ingredients: [
            { item: "raisins", amount: 2, unit: "cups" },
            { item: "water", amount: 3, unit: "cups" },
            { item: "shortening", amount: 1, unit: "cup" },
            { item: "sugar", amount: "1 1/2", unit: "cups" },
            { item: "eggs", amount: 3 },
            { item: "vanilla", unit: "to taste" },
            { item: "flour", amount: "3 3/4", unit: "cups" },
            { item: "cinnamon", amount: 1, unit: "tsp" },
            { item: "cloves", amount: "1/2", unit: "tsp" },
            { item: "baking soda", amount: 1, unit: "tsp" },
            { item: "baking powder", amount: 1, unit: "tsp" },
        ],
        instructions: [
            "Boil raisins in water until 1 cup water is left. Cool a little.",
            "Cream shortening and sugar together.",
            "Add eggs and vanilla to creamed mixture.",
            "Add raisin mixture to above.",
            "Mix in flour, cinnamon, cloves, baking soda, and baking powder.",
            "Drop on cookie sheet from a spoon.",
            "Bake (temperature and time not specified in original recipe).",
        ],
    },
    canadian_jam_cookies: {
        title: "Canadian Jam Cookies",
        servings: 2, // 2 dozen
        ingredients: [
            { item: "margarine", amount: "1/2", unit: "cup" },
            { item: "brown sugar", amount: "1/2", unit: "cup" },
            { item: "honey", amount: "1/4", unit: "cup" },
            { item: "egg", amount: 1 },
            { item: "vanilla", amount: "1/2", unit: "tsp" },
            { item: "flour", amount: "1 3/4", unit: "cups" },
            { item: "salt", amount: "1/4", unit: "tsp" },
            { item: "baking soda", amount: 1, unit: "tsp" },
            { item: "jam" },
        ],
        instructions: [
            "Cream butter, sugar, and honey.",
            "Beat egg and vanilla.",
            "Combine dry ingredients and blend into creamed mixture.",
            "Chill dough at least 30 minutes.",
            "Shape into balls. Flatten on baking sheet.",
            "Bake at 350°F for 8-10 minutes.",
            "Cool on baking sheet for a few minutes.",
            "Stick 2 cookies together with jam.",
        ],
    },
    rolo_cookies: {
        title: "Rolo Cookies",
        servings: 4, // 4 dozen
        ingredients: [
            { item: "all-purpose flour", amount: "2 1/2", unit: "cups" },
            { item: "unsweetened cocoa", amount: "3/4", unit: "cup" },
            { item: "baking soda", amount: 1, unit: "tsp" },
            { item: "sugar", amount: 1, unit: "cup" },
            { item: "brown sugar", amount: 1, unit: "cup" },
            { item: "margarine or butter, softened", amount: 1, unit: "cup" },
            { item: "vanilla", amount: 2, unit: "tsp" },
            { item: "eggs", amount: 2 },
            { item: "chopped pecans", amount: 1, unit: "cup" },
            { item: "Rolo chewy caramels in milk chocolate", amount: 48 },
            { item: "sugar (for coating)", amount: 1, unit: "tbsp" },
        ],
        instructions: [
            "Heat oven to 375°F.",
            "In a small bowl, combine flour, cocoa and baking soda; blend well.",
            "In a large bowl, beat 1 cup sugar, brown sugar and margarine until light and fluffy.",
            "Add vanilla and eggs; beat well.",
            "Add flour mixture; blend well.",
            "Stir in 1/2 cup of the pecans.",
            "For each cookie, with floured hands, shape about 1 tablespoon dough around 1 caramel candy, covering completely.",
            "In a small bowl, combine remaining 1/2 cup pecans and 1 tbsp sugar.",
            "Press one side of each ball into pecan mixture.",
            "Place, nut side up, 2 inches apart on ungreased cookie sheets.",
            "Bake for 7 to 10 minutes or until set and slightly cracked.",
            "Cool 2 minutes; remove from cookie sheets.",
            "Cool completely on wire rack.",
        ],
    },
    coconut_oatmeal_crisp_cookies: {
        title: "Coconut-Oatmeal Crisp Cookies",
        servings: 5, // Approximately 5 dozen (rounded from 65)
        ingredients: [
            { item: "margarine", amount: "3/4", unit: "cup" },
            { item: "sugar", amount: 1, unit: "cup" },
            { item: "brown sugar", amount: "1/2", unit: "cup" },
            { item: "eggs", amount: 2 },
            { item: "vanilla", amount: 2, unit: "tsp" },
            { item: "flour", amount: 1, unit: "cup" },
            { item: "baking powder", amount: 1, unit: "tsp" },
            { item: "baking soda", amount: "1/2", unit: "tsp" },
            { item: "salt", amount: 1, unit: "pinch" },
            { item: "coconut", amount: "1 1/4", unit: "cups" },
            { item: "rolled oats", amount: "2 1/2", unit: "cups" },
        ],
        instructions: [
            "Preheat oven to 375°F.",
            "In a large bowl, beat together margarine, sugar, brown sugar, eggs, and vanilla.",
            "Add flour, baking powder, baking soda, and salt.",
            "Stir in coconut and oats.",
            "Drop by teaspoonfuls, 3 inches apart, on ungreased baking sheets.",
            "Bake 10 to 12 minutes or until lightly browned.",
            "Cool 2 to 3 minutes on baking sheets; then remove to racks to cool completely.",
        ],
    },
    double_chocolate_chip_cookies: {
        title: "Double Chocolate Chip Cookies (Pam's Cookies)",
        servings: 3, // 3 dozen
        ingredients: [
            { item: "shortening", amount: 1, unit: "cup" },
            { item: "sugar", amount: 2, unit: "cups" },
            { item: "eggs", amount: 2 },
            { item: "vanilla", amount: 2, unit: "tsp" },
            { item: "flour", amount: 2, unit: "cups" },
            { item: "cocoa", amount: "3/4", unit: "cup" },
            { item: "baking soda", amount: 1, unit: "tsp" },
            { item: "salt", amount: "1/2", unit: "tsp" },
            { item: "chocolate chips", amount: 2, unit: "cups" },
        ],
        instructions: [
            "Cream together shortening and sugar.",
            "Add eggs and vanilla, mix well.",
            "In a separate bowl, combine flour, cocoa, baking soda, and salt.",
            "Gradually add dry ingredients to the creamed mixture.",
            "Stir in chocolate chips.",
            "Bake at 350°F for 11 1/2 minutes.",
        ],
    },
    easy_shortbread: {
        title: "Easy Shortbread",
        servings: 4, // 4 dozen
        ingredients: [
            { item: "butter (or margarine)", amount: 2, unit: "lbs" },
            { item: "icing sugar", amount: 2, unit: "cups" },
            { item: "cornstarch", amount: 1, unit: "cup" },
            { item: "flour", amount: 6, unit: "cups" },
            { item: "almond flavoring", unit: "to taste" },
            { item: "vanilla flavoring", unit: "to taste" },
            { item: "salt", unit: "few grains" },
        ],
        instructions: [
            "Cream butter and sugar.",
            "Add other ingredients.",
            "Roll in ball; flatten with a fork.",
            "Bake at 325°F (or 350°F) for 20 minutes.",
        ],
    },
    ginger_cream_cookies: {
        title: "Ginger Cream Cookies",
        servings: 2, // 2 dozen
        ingredients: [
            { item: "soft shortening", amount: "1/4", unit: "cup" },
            { item: "sugar", amount: "1/2", unit: "cup" },
            { item: "egg", amount: 1 },
            { item: "molasses", amount: "1/2", unit: "cup" },
            { item: "hot water", amount: "1/2", unit: "cup" },
            { item: "baking soda", amount: 1, unit: "tsp" },
            { item: "sifted flour", amount: 2, unit: "cups" },
            { item: "salt", amount: "1/2", unit: "tsp" },
            { item: "ginger", amount: 1, unit: "tsp" },
            { item: "nutmeg", amount: "1/2", unit: "tsp" },
            { item: "cloves", amount: "1/2", unit: "tsp" },
            { item: "cinnamon", amount: "1/2", unit: "tsp" },
        ],
        instructions: [
            "Mix shortening and sugar together.",
            "Add egg and molasses.",
            "Dissolve baking soda in hot water and stir into mixture.",
            "Sift together flour, salt, and spices. Stir into mixture.",
            "Chill dough.",
            "Drop teaspoonfuls about 2 inches apart on lightly greased sheet.",
            "Bake at 400°F for 7-8 minutes.",
        ],
    },
    gingerbread_for_houses: {
        title: "Gingerbread for Houses",
        servings: 1, // Keeping as is since it's for a house, not individual cookies
        ingredients: [
            { item: "shortening", amount: "1/2", unit: "cup" },
            { item: "sugar", amount: "1/2", unit: "cup" },
            { item: "dark molasses", amount: "1/2", unit: "cup" },
            { item: "egg", amount: 1 },
            { item: "flour", amount: "2 1/2", unit: "cups" },
            { item: "baking soda", amount: "1/2", unit: "tsp" },
            { item: "salt", amount: "1/2", unit: "tsp" },
            { item: "ginger", amount: 1, unit: "tsp" },
            { item: "cinnamon", amount: 1, unit: "tsp" },
            { item: "cloves", amount: 1, unit: "tsp" },
        ],
        instructions: [
            "Mix all ingredients together.",
            "Roll out on lightly greased cookie sheet.",
            "Cut out house shapes with a knife in the dough on the cookie sheet, leaving excess to bake as well.",
            "Bake at 350°F for about 15 minutes.",
            "Draw over the shapes again and let gingerbread completely cool.",
            "When cool, remove them from the cookie sheet and let them dry out completely, preferably overnight.",
            "Put the house together in stages, allowing each part to dry before the next stage.",
            "Start with the 4 walls and then add the roof.",
        ],
    },
    royal_icing: {
        title: "Royal Icing (for gingerbread houses)",
        servings: 1, // Keeping as is since it's for decorating, not individual servings
        ingredients: [
            { item: "egg white", amount: 1 },
            { item: "flavoring (vanilla or almond)", unit: "to taste" },
            { item: "icing sugar", amount: "enough to make a stiff icing" },
        ],
        instructions: [
            "Mix all ingredients together until a stiff icing is formed.",
            "Use to glue the gingerbread house together and to attach candies.",
        ],
    },
    gingerbread_men: {
        title: "Gingerbread Men",
        servings: 2, // 2 dozen
        ingredients: [
            { item: "butter", amount: "3/4", unit: "cup" },
            { item: "sugar", amount: 1, unit: "cup" },
            { item: "eggs", amount: 2 },
            { item: "dark molasses", amount: 1, unit: "cup" },
            { item: "sour cream", amount: "1/2", unit: "cup" },
            { item: "flour", amount: 5, unit: "cups" },
            { item: "salt", amount: "1/2", unit: "tsp" },
            { item: "cinnamon", amount: 1, unit: "tsp" },
            { item: "ginger", amount: 1, unit: "tsp" },
            { item: "baking soda", amount: 2, unit: "tsp" },
        ],
        instructions: [
            "Mix all ingredients together.",
            "Chill the dough.",
            "Roll 1/4 inch thick.",
            "Cut into gingerbread men shapes.",
            "Bake on ungreased sheet at 375°F (time not specified in original recipe).",
        ],
    },
    pumpkin_chocolate_chip_cookies: {
        title: "Pumpkin Chocolate Chip Cookies",
        servings: 4, // 4 dozen
        ingredients: [
            { item: "shortening", amount: 2, unit: "cups" },
            { item: "sugar", amount: 2, unit: "cups" },
            { item: "canned pumpkin", amount: 29, unit: "oz" },
            { item: "eggs", amount: 2 },
            { item: "vanilla", amount: 2, unit: "tsp" },
            { item: "flour", amount: 4, unit: "cups" },
            { item: "baking soda", amount: 2, unit: "tsp" },
            { item: "baking powder", amount: 2, unit: "tsp" },
            { item: "salt", amount: 1, unit: "tsp" },
            { item: "cinnamon", amount: 2, unit: "tsp" },
            { item: "ginger", amount: 2, unit: "tsp" },
            { item: "nutmeg", amount: 2, unit: "tsp" },
            { item: "cloves", amount: 2, unit: "tsp" },
            { item: "allspice", amount: 2, unit: "tsp" },
            { item: "chocolate chips", unit: "to taste" },
        ],
        instructions: [
            "Mix all ingredients together.",
            "Add chocolate chips to taste.",
            "Bake at 350°F for 12-13 minutes.",
        ],
    },
    pumpkin_cookie_glaze: {
        title: "Pumpkin Cookie Glaze",
        servings: 4, // 4 dozen (to match pumpkin cookies)
        ingredients: [
            { item: "butter", amount: "2/3", unit: "cup" },
            { item: "milk", amount: 1, unit: "cup" },
            { item: "brown sugar", amount: 2, unit: "cups" },
            { item: "powdered sugar", amount: 3, unit: "cups" },
        ],
        instructions: [
            "Mix butter, milk, and brown sugar together.",
            "Boil for 3 minutes.",
            "Cool completely.",
            "Add powdered sugar.",
            "Drizzle over cooled pumpkin cookies.",
        ],
    },
    sugar_cookies: {
        title: "Sugar Cookies",
        servings: 4, // 4 dozen
        ingredients: [
            { item: "shortening", amount: "1 1/2", unit: "cups" },
            { item: "sugar", amount: "2 1/4", unit: "cups" },
            { item: "eggs", amount: 4 },
            { item: "vanilla", amount: 1, unit: "tsp" },
            { item: "almond extract", amount: 1, unit: "tsp" },
            { item: "lemon extract", amount: 1, unit: "tsp" },
            { item: "flour", amount: 5, unit: "cups" },
            { item: "baking powder", amount: 2, unit: "tsp" },
            { item: "salt", amount: 2, unit: "tsp" },
        ],
        instructions: [
            "Cream shortening, sugar, eggs, and flavorings.",
            "Add dry ingredients.",
            "Mix well.",
            "Chill for 1 hour.",
            "Roll 1/4 inch thick.",
            "Bake on greased pans at 400°F for 4-6 minutes.",
        ],
    },
};

export default cookieRecipes;
